#!/usr/bin/env bash
# Generate the Slack app manifest for the Hermes Slack platform.
#
# The manifest declares every Hermes slash command, OAuth scope, and event
# subscription, and enables Socket Mode. Paste its contents into Slack's
# "Create New App -> From an app manifest" flow.
#
# The manifest must be generated by the same Hermes version that runs the
# gateway, so this script executes the command inside the hermes container.
#
# The Hermes CLI writes the manifest to "$HOME/.hermes/slack-manifest.json".
# HOME differs inside the container: the daemon runs with HOME=/opt/data, while
# `docker exec` sessions default to HOME=/opt/data/home. Only /opt/data is the
# host-mounted volume, so this script pins HOME=/opt/data and then verifies the
# file exists there instead of guessing the path.
#
# Usage:
#   bash modules/hermes/scripts/slack-manifest.sh
#
# Environment overrides:
#   SLACK_MANIFEST_BOT_NAME             bot display name (default: Hermes)
#   SLACK_MANIFEST_DESCRIPTION_FILE     file with Slack's long description
#   HERMES_CONTAINER                    container name (default: hermes)
#   HERMES_CONTAINER_DATA_DIR           mounted data dir (default: /opt/data)
#   HERMES_DATA_DIR                     its host path
#
# See modules/hermes/SLACK.md for the full setup walkthrough.
set -euo pipefail

CONTAINER="${HERMES_CONTAINER:-hermes}"
# Container path of the host-mounted Hermes data volume.
CONTAINER_DATA_DIR="${HERMES_CONTAINER_DATA_DIR:-/opt/data}"
# Host path that the data volume is mounted from (override when it differs).
HOST_DATA_DIR="${HERMES_DATA_DIR:-/home/runner/data/hermes/data}"

# Long app description shown on the Slack app's About tab. Optional: the
# command works without it, but Slack requires 175-4000 characters when set.
DESCRIPTION_FILE="${SLACK_MANIFEST_DESCRIPTION_FILE:-}"

# Bot display name baked into the manifest. The Hermes generator defaults to
# "Hermes"; set this to the name the installed Slack app actually uses, or
# re-applying the manifest renames the bot.
BOT_NAME="${SLACK_MANIFEST_BOT_NAME:-Hermes}"

if ! command -v docker >/dev/null 2>&1; then
    echo "error: docker not found; run this on a host with the hermes container" >&2
    exit 1
fi

if ! docker ps --format '{{.Names}}' | grep -qx "$CONTAINER"; then
    echo "error: container '$CONTAINER' is not running" >&2
    echo "hint: start it with the deploy pipeline, or set HERMES_CONTAINER" >&2
    exit 1
fi

echo "Generating Slack app manifest inside '$CONTAINER'..."

# Equivalent to running, inside the container:
#   hermes slack manifest --agent-view --write
# Executed as an argv array so no word splitting or globbing is applied.
ARGS=(slack manifest --agent-view --write)
# Keep the installed bot name instead of the generator's "Hermes" default.
ARGS+=(--name "$BOT_NAME")
if [ -n "$DESCRIPTION_FILE" ]; then
    # The description file must exist inside the container; mount it or copy it
    # into /opt/data first.
    ARGS+=(--long-description-file "$DESCRIPTION_FILE")
fi

# Remove any previous manifest first, so a stale file can never be mistaken for
# the output of this run.
docker exec -e "HOME=${CONTAINER_DATA_DIR}" "$CONTAINER" \
    sh -c 'rm -f "$HOME/.hermes/slack-manifest.json"'

# Pin HOME to the mounted volume so the manifest lands on the host mount.
docker exec -e "HOME=${CONTAINER_DATA_DIR}" "$CONTAINER" hermes "${ARGS[@]}"

# Locate the file the CLI actually wrote rather than trusting a hardcoded path.
MANIFEST_PATH=$(docker exec -e "HOME=${CONTAINER_DATA_DIR}" "$CONTAINER" \
    sh -c 'ls -1 "$HOME/.hermes/slack-manifest.json" 2>/dev/null || find "$HOME" -maxdepth 3 -name slack-manifest.json 2>/dev/null | head -1')

if [ -z "$MANIFEST_PATH" ]; then
    echo "error: manifest was not found under ${CONTAINER_DATA_DIR} in '$CONTAINER'" >&2
    echo "hint: the CLI printed its own path above; check that HOME is writable" >&2
    exit 1
fi

# Map the container path onto the host mount so the printed command works.
HOST_MANIFEST_PATH="${HOST_DATA_DIR}/${MANIFEST_PATH#"${CONTAINER_DATA_DIR}"/}"

echo
echo "Manifest written inside the container at: $MANIFEST_PATH"
echo "Read it on the host with:"
echo "  sudo cat ${HOST_MANIFEST_PATH}"
echo
echo "Next: paste the contents into https://api.slack.com/apps"
echo "  Create New App -> From an app manifest -> pick workspace -> paste -> Create"
echo "See modules/hermes/SLACK.md for the remaining steps."
