#!/usr/bin/env bash
# Generate the Slack app manifest for the Hermes Slack platform.
#
# The manifest declares every Hermes slash command, OAuth scope, and event
# subscription, and enables Socket Mode. Paste its contents into Slack's
# "Create New App -> From an app manifest" flow.
#
# The manifest must be generated by the same Hermes version that runs the
# gateway, so this script executes the command inside the hermes container.
# The file is written to the host-mounted data volume, so it survives restarts
# and is readable from the host without copying.
#
# Usage:
#   bash modules/hermes/scripts/slack-manifest.sh
#
# Then read it on the production host with:
#   sudo cat /home/runner/data/hermes/data/slack-manifest.json
#
# See modules/hermes/SLACK.md for the full setup walkthrough.
set -euo pipefail

CONTAINER="${HERMES_CONTAINER:-hermes}"
# Container path; /opt/data is the host-mounted data volume.
MANIFEST_PATH="/opt/data/slack-manifest.json"
# Host-side path for the printed hint (override when data lives elsewhere).
HOST_DATA_DIR="${HERMES_DATA_DIR:-/home/runner/data/hermes/data}"

# Long app description shown on the Slack app's About tab. Optional: the
# command works without it, but Slack requires 175-4000 characters when set.
DESCRIPTION_FILE="${SLACK_MANIFEST_DESCRIPTION_FILE:-}"

if ! command -v docker >/dev/null 2>&1; then
    echo "error: docker not found; run this on a host with the hermes container" >&2
    exit 1
fi

if ! docker ps --format '{{.Names}}' | grep -qx "$CONTAINER"; then
    echo "error: container '$CONTAINER' is not running" >&2
    echo "hint: start it with the deploy pipeline, or set HERMES_CONTAINER" >&2
    exit 1
fi

echo "Generating Slack app manifest inside '$CONTAINER'..."

# Equivalent to running, inside the container:
#   hermes slack manifest --agent-view --write
# Executed as an argv array so no word splitting or globbing is applied.
ARGS=(slack manifest --agent-view --write)
if [ -n "$DESCRIPTION_FILE" ]; then
    # The description file must exist inside the container; mount it or copy it
    # into /opt/data first.
    ARGS+=(--long-description-file "$DESCRIPTION_FILE")
fi

docker exec "$CONTAINER" hermes "${ARGS[@]}"

echo
echo "Manifest written to the container path: $MANIFEST_PATH"
echo "Read it on the host with:"
echo "  sudo cat ${HOST_DATA_DIR}/slack-manifest.json"
echo
echo "Next: paste the contents into https://api.slack.com/apps"
echo "  Create New App -> From an app manifest -> pick workspace -> paste -> Create"
echo "See modules/hermes/SLACK.md for the remaining steps."
